config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "home#index"
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :recent, ->{order created_at: :desc}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :code, presence: true, uniqueness: true, length: {maximum: 50, minimum: 2}
  validates :name, presence: true, length: {maximum: 255, minimum: 2}
  validates :description, length: {maximum: 1000}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < DashboardController
  before_action :load_category, only: [:edit, :update, :destroy, :show]

  def index
    @search = Category.ransack params[:q]
    @per_page = params[:per_page] || Settings.per_pages.second
    @categories = @search.result.recent.page(params[:page]).per @per_page
    respond_to :js if request.xhr?
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "admin.messages.create_success", name: t("admin.forders.category").downcase
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.messages.update_success", name: t("admin.forders.category").downcase
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] =  t "admin.messages.delete_success", name: t("admin.forders.category").downcase
    else
      flash[:error] = t "admin.messages.delete_fail", name: t("admin.forders.category").downcase
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :code, :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "admin.messages.not_found", name: t("admin.forders.category").downcase
    redirect_to admin_categories_path
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < DashboardController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController
  layout "dashboard"

  # before_action :authenticate_admin!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td class="table__col-w5 table__col-center"><%= category.id %></td>
  <td class="table__col-w15"><%= category.code %></td>
  <td class="table__col-w30"><%= category.name %></td>
  <td class="table__col-w40"><%= category.description %></td>
  <td class="table__col-w10 table__col-center">
    <%= link_to "#", class: "btn btn-xs btn-default" do %>
      <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_admin_category_path(category), class: "btn btn-xs btn-warning" do %>
      <i class="fa fa-pencil"></i>
    <% end %>
    <%= link_to admin_category_path(category), method: :delete, class: "btn btn-xs btn-danger",
      data: {confirm: t("admin.messages.confirm", name: category.name)} do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Quick Example</h3>
  </div>
  <div class="row">
    <%= simple_form_for [:admin, category], html: {class: "col-md-offset-2 col-md-8"} do |f| %>
      <div class="box-body">
        <%= render partial: "admin/form/input", collection: %i(code name), as: :attribute,
          locals: {form: f, placeholder: nil} %>
        <%= render "admin/form/textarea", attribute: :description, form: f, rows: 5, placeholder: nil %>
      </div>
      <div class="box-footer">
        <center>
          <%= f.button :submit, yield(:button_submit), class: "btn btn-primary form__input--color-white" %>
        </center>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/_search.html.erb
<div class="title--pad-10">
  <div class="panel panel-default">
    <div class="panel-heading"><%= t ".name"%></div>
    <div class="panel-body">
      <%= search_form_for [:admin, @search], class: "row col-md-offset-2", remote: true do |f| %>
        <div class="form-group col-md-7">
          <%= f.text_field :code_or_name_or_description_cont, placeholder: "Nhập mã hoặc tên danh mục hoặc mô tả",
            class: "form-control" %>
        </div>
        <%= link_to admin_categories_path, class: "col-md-1" do %>
          <i class="fa fa-refresh btn btn-success"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_table_category.html.erb
<div class="box-body">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th class="table__col-w5 table__col-center">
          <%= sort_link @search, :id, Category.human_attribute_name(:id), {}, {remote: true} %>
        </th>
        <th class="table__col-w15">
          <%= sort_link @search, :id, Category.human_attribute_name(:code), {}, {remote: true} %>
        </th>
        <th class="table__col-w30">
          <%= sort_link @search, :id, Category.human_attribute_name(:name), {}, {remote: true} %>
        </th>
        <th class="table__col-w40">
          <%= sort_link @search, :id, Category.human_attribute_name(:description), {}, {remote: true} %>
        </th>
        <th class="table__col-w10 table__col-center"><%= t ".action" %></th>
      </tr>
      <%= render partial: "category", collection: @categories, as: :category %>
    </tbody>
  </table>
</div>
<div class="box-footer clearfix">
  <%= paginate @categories, remote: true %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :button_submit, t(".button_update") %>
<%= render "form", category: @category %>

app/views/admin/categories/index.html.erb
<div class="box">
  <%= render "search" %>
  <div class="box-header with-border">
    <h3 class="box-title"><%= t ".title" %></h3>
  </div>
  <div class="title--pad-l10-t10">
    <%= link_to new_admin_category_path, class: "btn btn-sm btn-success" do %>
      <i class="fa fa-plus"></i> <%= t ".new" %>
    <% end %>
    <div id="example1_length" class="pull-right title--pad-r10">
      <label>
        <%= select_tag :per_page,
          options_for_select(Settings.per_pages.as_json.map{|key, value| [value, value]}, @per_page),
          class: "form-control input-sm", data: {remote: true, url: admin_categories_path} %>
      </label>
    </div>
  </div>
  <div id="not-exist-categories-search" class="title--pad-l10-t10"></div>
  <div id="list-categories">
    <%= render "table_category" %>
  </div>
</div>

app/views/admin/categories/index.js.erb
$('#list-categories').html('<%= j render("table_category") %>');
$('#not-exist-categories-search').html('<%= t("admin.search.not_found") if @search.result.blank? %>');

app/views/admin/categories/new.html.erb
<% provide :button_submit, t(".button_create") %>
<%= render "form", category: @category %>

app/views/admin/form/_input.html.erb
<div class="form-group">
  <%= form.label attribute, label: false, wrapper: false, error: false %>
  <%= form.input attribute, label: false, wrapper: false, error: false, class: "form-control", placeholder: placeholder || nil %>
  <%= form.full_error attribute, class: "form__item-error" %>
</div>

app/views/admin/form/_textarea.html.erb
<div class="form-group">
  <%= form.label attribute, label: false, wrapper: false, error: false %>
  <%= form.input attribute, as: :text, label: false, wrapper: false, error: false, class: "form-control",
    placeholder: placeholder, input_html: {rows: rows}%>
  <%= form.full_error attribute, class: "form__item-error" %>
</div>

app/views/admin/home/index.html.erb
<%= render "layouts/admin/content" %>

app/views/layouts/admin/_color_sidebar.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-user bg-yellow"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

              <p>New phone +1(800)555-1234</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

              <p>nora@example.com</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-file-code-o bg-green"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

              <p>Execution time 5 seconds</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Update Resume
              <span class="label label-success pull-right">95%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-success" style="width: 95%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Laravel Integration
              <span class="label label-warning pull-right">50%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Back End Framework
              <span class="label label-primary pull-right">68%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Allow mail redirect
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Other sets of options are available
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Expose author name in posts
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Allow the user to show his name in blog posts
          </p>
        </div>
        <!-- /.form-group -->

        <h3 class="control-sidebar-heading">Chat Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Show me as online
            <input type="checkbox" class="pull-right" checked>
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Turn off notifications
            <input type="checkbox" class="pull-right">
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Delete chat history
            <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
          </label>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>

app/views/layouts/admin/_content_header.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Developers
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Sales Department
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Reviewers
                      <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                    page and may cause design problems
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> 5 new members joined
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks: style can be found in dropdown.less -->
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Create a nice theme
                      <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Some task I need to do
                      <small class="pull-right">60%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">60% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Make beautiful transitions
                      <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
            <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitsu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Mitsu</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "dashboard", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "dashboard", "data-turbolinks-track": "reload" %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- header -->
      <%= render "layouts/admin/header" %>
      <!-- /header -->
      <aside class="main-sidebar">
        <!-- sidebar -->
        <section class="sidebar">
          <%= render "layouts/admin/sidebar" %>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <%= render "layouts/admin/content_header" %>
        <section class="content">
          <%= yield %>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.4.0
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
        reserved.
      </footer>

      <!-- Control Sidebar -->
      <%= render "layouts/admin/color_sidebar" %>
      <!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
  </body>
</html>